<?php
/**
Author: ADEFOKUN Tomiwa M.
Email: Tomiwa.adefokun@progenicscorp.com,tomiwa.adefokun@gmail.com,tomiwa.adefokun@gmail.com
*/

?>
<?php if($this->data): ?>
<div class="subContent">
<?php if($this->title):?>
<div class="blockTitle"><?php echo  $this->title;?></div>
<?php endif;?>
	<div>
<table width="100%" class="block">
				<?php  foreach($this->data as $v): 
				   
                   $dto = $this->getDto($v);
				?>
				<tr>
					<td>
					<div class="title">
					<a href="javascript:loadMainById(<?php echo $dto->getField($this->primaryKey);?>)"><?php echo  $dto->getField('item_title')?></a></div>
					<div class="text">
					<?php echo  
					(($item_desc = $dto->getField('item_desc')) != '') 
					? $this->highlight($item_desc) 
					: $this->highlight($dto->getField('item_details'));
					?>
					</div>
					</td>
					
				</tr>
			<?php endforeach ?>
		
		</table>	
		
	</div>
	</div>
 <?php endif ?>