<?php 
if(isset($this->data)){
?>
<div class='pageSubTitle'><?php echo  $this->title;?></div>
<?php 
	$tabs = $this->createWidget('Panes_Tabs'); 
	$tabs->setProperty('containerName','page_'.$this->contentPageName);
	$i = 1;
	if($this->tab) $defaultTab = 0;
	foreach($this->data as $v){
	    if($this->tab && $this->tab == $v['item_subcat']) $defaultTab = $i;

		if($this->tab) $tabs->setProperty('defaultTab',$defaultTab);
		
	    $tabLabel = ($v['item_pane_label'] != '') ? $v['item_pane_label'] : $v['item_title'];
		
		$content = $v['item_details'];
		$paneContent = '';
		if($v['item_title'] != '') $paneContent .= '<div class=\'subContentTitle\'>'.$v['item_title'].'</div>';
		
		$subAttch = unserialize(base64_decode($v['item_attch']));

		if(count($subAttch) > 0){
			$downloadsAttch = '';
			$subAttchDisp = "<table align='left' style='margin: 10 0 10 0'><tr>";
				if(is_array($subAttch)):
					foreach($subAttch as $v){
						$label = FController::mystripslashes($v['label']);
					   
						$type = strtolower($v['type']);
						$imgTypes = array('gif','jpg','bmp','jpeg'); 
						if(in_array($type,$imgTypes)){ 
							$subAttchDisp .= "<td style='padding-right: 10px;'><div style='border: 1px solid #cccccc; padding: 8px;'>";
							$subAttchDisp .= "<img src='".$this->getConf()->path['uploadUrl']."/content/".$v['filename']."' height='100px' style='border: 0px'/>";
							if($label != '')$subAttchDisp .= "<div style='background-color: #dddddd;padding: 2px; font-size: 11px; color: #004d84;'>".$label."</div>";
							$subAttchDisp .= "</div></td>";
						}
						else $downloadsAttch .= "<li><a href='".$this->getConf()->path['uploadUrl'].'/content/'.$v['filename']."' target='_blank'>".$label."</a>";

					}
				endif;
			$subAttchDisp .= "</tr></table>";
			$paneContent .= $subAttchDisp;
	   }
		
	   $paneContent .= html_entity_decode($content);
	   $paneContent .= $downloadsAttch;
		
		
		$tabs->add($tabLabel,$paneContent);
		$i++;
	}
	
	$tabs->build();
	$tabs->display();
}

?>