<?php 
/**
Author: ADEFOKUN Tomiwa M.
Email: tomiwa.adefokun@gmail.com
*/

?>
<div class='pageTitle'><?php echo  $this->title;?></div>
<p>
	 <?php  if($this->data): ?>
	 
	<table>
			<?php  $i = (isset($this->pager)) ? $this->pager['offset'] + 1 : 1; foreach($this->data as $v): 
			   
			   $dto = $this->getDto($v);
			?>
			<tr <?php echo  $this->setAltBg($i,'#dddddd');?> ><td>
			     <table cellpadding="2" width="350px">
				    <tr>
						<th width="100px" align="left">First Name</th><td><?php echo  $dto->getField('employee_firstname')?></td>
					</tr>
					<tr>
						<th width="100px" align="left">Last Name</th><td valign='top'><?php echo  $dto->getField('employee_lastname')?></td>
					</tr>
					<tr>
						<th width="100px" align="left">Address</th><td valign='top'><?php echo  $dto->getField('employee_address')?></td>
					</tr>
			    </table>
			</td></tr>
		<?php  $i++; endforeach ?>
	
	</table>	
	
	<?php if($this->pager):
		echo $this->contentPager($this->pager,true,'demo_blocks_page');
	endif;
	?>
	 <?php  else: ?>
		No employee on list.
	 <?php  endif ?>
</p>
