<?php 
/**
Author: ADEFOKUN Tomiwa M.
Email: Tomiwa.adefokun@progenicscorp.com,tomiwa.adefokun@gmail.com,tomiwa.adefokun@gmail.com
*/

?>
<div class='pageTitle'><?php echo  $this->title;?></div>
<div>
<a href="<?php echo  $this->setUrl(null,'list');?>">Show all</a> | 
<a href="<?php echo  $this->setUrl(null,'add');?>">Add new</a> | 
<a href="javascript: history.back(1);">Back</a>

</div>

<!-- Error display-->
<?php $this->renderErrors(); ?>

<!-- List section-->
<?php  if(isset($this->list)): ?>
	<p>
	     <?php  if($this->data): ?>
		 <form name="list" action="<?php echo $this->setUrl(null,'delete');?>" method="post">
           <table width="100%" class="excel" >
				<thead>
				<th width="50px">&nbsp;</th><th><b>Role Name</th><th><b>Role Key</th><th width="60px">&nbsp;</th>
				</thead>
				<?php  $i = (isset($this->pager)) ? $this->pager['offset'] + 1 : 1; foreach($this->data as $v): 
				   
                   $dto = $this->getDto($v);
				?>
				<tr <?php echo  $this->setAltBg($i);?> ><td><input type="checkbox" name="delete[]" value="<?php echo  $dto->getField($this->primaryKey);?>"/> <?php echo  $i;?></td>
					<td><?php echo  $dto->getField('role_name')?></td>
					<td valign='top'><?php echo  $dto->getField('role_key')?>&nbsp;</td>
					<td valign='top'><nobr><a href="#" onclick="if(confirm('The item will be removed completely!'))self.location = '<?php echo  $this->setUrl(array('eid'=>$dto->getField($this->primaryKey)),'delete');?>';">
						<img  src="<?php echo $this->getBaseUrl();?>/freedom/images/delete.png" align='right' border=0 title="Delete" alt='Delete'/>
					    </a> 
					    <a href="<?php echo $this->setUrl(array('eid'=>$dto->getField($this->primaryKey)),'edit');?>>">
					    	<img src="<?php echo $this->getBaseUrl();?>/freedom/images/edit.png" border=0 title="Edit" alt='Edit'/></a>&nbsp;&nbsp;&nbsp;</nobr>
					    	
					</td>
				</tr>
			<?php  $i++; endforeach ?>
		</table>
					<div align="right" class="tinyText"><input type="checkbox" value="0" onclick="doSelect('list','delete[]',this.checked)"> Select or unselect all items <input type="submit" value="Delete Selected"></div>
		</form>
		<?php if($this->pager):
	        echo $this->contentPager($this->pager);
		endif;
		?>
             <?php  else: ?>
                No contents to display.
             <?php  endif ?>
	</p>

<?php  endif ?>

<?php  if(isset($this->edit)): 
   $dto = $this->getDto($this->data,$this->modelName);
?>
	<p>

		<form action="<?php echo  $this->setUrl(array('eid'=>$this->getParam('eid')),$this->postAction) ?>" method="post">
			<table class="excel excelOrdinary">
				<tr>
					<th align='left'>Role Name: </th>
					<td><input name="<?php echo  $dto->setField('role_name');?>" style='width: 400px' value="<?php echo  $dto->getField('role_name')?>"/></td>
				</tr>				
				<tr>
					<th align='left'>Role Key: </th>
					<td><input name="<?php echo  $dto->setField('role_key');?>" style='width: 400px' value="<?php echo  $dto->getField('role_key')?>" <?php $this->isReadOnly(array('0','1'),$dto->getField('role_key'));?> /></td>
				</tr>
				
				<tr>
					<td  >
						<input type="hidden" name="eid" value="<?php echo  $dto->getField($this->primaryKey);?>">
						</td>
						<td>
						<input type="submit" name="<?php echo  $this->action ?>" value="<?php echo  $this->actionLabel ?>">
						<input type="button" value="Cancel" onclick="window.location = '<?php echo $this->setUrl(null,'list');?>'">
					</td>
				</tr>
			</table>
		</form>
		
	</p>
	<h5>NOTE:</h5> 
	<li>The Admin key must be 1
	<li>The Ordinary User key must be 0

	
<?php  endif ?>