<?php 
/**
Author: ADEFOKUN Tomiwa M.
Email: Tomiwa.adefokun@progenicscorp.com,tomiwa.adefokun@gmail.com,tomiwa.adefokun@gmail.com
*/

?>
<div class='pageTitle'><?php echo  $this->title;?></div>
<div>
<a href="<?php echo  $this->setUrl(null,'list');?>">Show all</a> | 
<a href="<?php echo  $this->setUrl(null,'add');?>">Add new</a> | 
<a href="javascript: history.back(1);">Back</a>

</div>

<!-- Error display-->
<?php $this->renderErrors() ?>

<!-- List section-->
<?php  if(isset($this->list)): ?>
	<p>
	     <?php  if($this->data): ?>
		<form name="list" action="<?php echo $this->setUrl(null,'delete');?>" method="post">
		<table width="100%" class="excel" >
				<thead>
				<th width="50px">&nbsp;</th><th><b>First Name</th><th><b>Last Name</th><th><b>Email Address</th><th width="60px">&nbsp;</th>
				</thead>
				<?php  $i = (isset($this->pager)) ? $this->pager['offset'] + 1 : 1; foreach($this->data as $v): 
				   
                   $dto = $this->getDto($v);
				?>
				<tr <?php echo  $this->setAltBg($i);?> ><td><input type="checkbox" name="delete[]" value="<?php echo  $dto->getField($this->primaryKey);?>"/> <?php echo  $i;?></td>
					<td><?php echo  $dto->getField('firstname')?></td>
					<td valign='top'><?php echo  $dto->getField('lastname')?>&nbsp;</td>
					<td valign='top'><?php echo  $dto->getField('email_address')?>&nbsp;</td>
					<td valign='top'><nobr><a href="#" onclick="if(confirm('The item will be removed completely!'))self.location = '<?php echo  $this->setUrl(array('eid'=>$dto->getField($this->primaryKey)),'delete');?>';">
						<img  src="<?php echo $this->getBaseUrl();?>/freedom/images/delete.png" align='right' border=0 title="Delete" alt='Delete'/>
					    </a> 
					    <a href="<?php echo $this->setUrl(array('eid'=>$dto->getField($this->primaryKey)),'edit');?>">
					    	<img src="<?php echo $this->getBaseUrl();?>/freedom/images/edit.png" border=0 title="Edit" alt='Edit'/></a>&nbsp;&nbsp;&nbsp;</nobr>
					    	
					</td>
				</tr>
			<?php  $i++; endforeach ?>
			</table>
		
				<div align="right" class="tinyText"><input type="checkbox" value="0" onclick="doSelect('list','delete[]',this.checked)"> Select or unselect all items <input type="submit" value="Delete Selected"></div>
		</form>
		<?php if($this->pager):
	        echo $this->contentPager($this->pager);
		endif;
		?>
             <?php  else: ?>
                No contents to display.
             <?php  endif ?>
	</p>

<?php  endif ?>

<?php  if(isset($this->edit)): 
   $dto = $this->getDto($this->data,$this->modelName);
?>
	<p>

		<form action="<?php echo  $this->setUrl(array('eid'=>$this->getParam('eid')),$this->postAction) ?>" method="post">
			<table class="excel excelOrdinary">
				<tr>
					<th align='left'>Last Name: </th>
					<td><input name="<?php echo  $dto->setField('lastname');?>" style='width: 400px' value="<?php echo  $dto->getField('lastname')?>"/></td>
				</tr>				
				<tr>
					<th align='left'>First Name: </th>
					<td><input name="<?php echo  $dto->setField('firstname');?>" style='width: 400px' value="<?php echo  $dto->getField('firstname')?>"/></td>
				</tr>				
				<tr>
					<th align='left'>User Role: </th>
					<td><select name="<?php echo  $dto->setField('user_role');?>">
                        <option value="0"/>--Select</option>
						<?php echo  $this->generateOptions($this->roles,$dto->getField('user_role','0'));?>
						</select>
				    </td>
				</tr>				
				<tr>
					<th align='left'>Email Address: </th>
					<td><input name="<?php echo  $dto->setField('email_address');?>" style='width: 400px' value="<?php echo  $dto->getField('email_address')?>"/></td>
				</tr>				
				<tr>
					<th align='left'>Security Question: </th>
					<td><input name="<?php echo  $dto->setField('security_question');?>" style='width: 400px' value="<?php echo  $dto->getField('security_question')?>"/></td>
				</tr>				
				<tr>
					<th align='left'>Answer: </th>
					<td><input name="<?php echo  $dto->setField('security_answer');?>" style='width: 400px' value="<?php echo  $dto->getField('security_answer')?>"/></td>
				</tr>				
				<tr>
					<td align='left'></td>
					<td>
						<h5><input type="checkbox" onclick="document.getElementById('manage_credential').style.display = (document.getElementById('manage_credential').style.display == 'none') ? 'block' : 'none'" name="edit_credentials"> Manage Credentials</h5>
						<table id="manage_credential" style="display: none">
						<tr><td>Username:</td><td><input name="username" value="<?php echo ($this->action == 'edit') ? $dto->getField('username') : ''?>"/></td></tr>
						<tr><td>Password:</td><td><input name="password" type="password" /></td></tr>
						<tr><td>Confirm Password:</td><td><input name="cpassword" type="password" /></td></tr>
						</table>
					</td>
				</tr>
				<tr>
					<td  >
						<input type="hidden" name="eid" value="<?php echo  $dto->getField($this->primaryKey);?>">
						</td>
						<td>
						<input type="submit" name="<?php echo  $this->action ?>" value="<?php echo  $this->actionLabel ?>">
						<input type="button" value="Cancel" onclick="window.location = '<?php echo $this->setUrl(null,'list');?>'">
					</td>
				</tr>
			</table>
		</form>
	</p>
<?php  endif ?>