<?php 
/**
Author: ADEFOKUN Tomiwa M.
Email: Tomiwa.adefokun@progenicscorp.com,tomiwa.adefokun@gmail.com
*/
?>

<!-- Error display-->
<?php $this->renderErrors() ?>


<!-- List section-->
	<p>
	     <?php  if($this->data): ?>
	     <?php // $this->addSearchBlock(); ?>
	     <form name="list" action="<?php echo $this->setUrl(array('pagename'=>$this->contentPageName),'delete');?>" method="post">
	   <table width="100%" class="excel" >
				<thead>
				<th width="50px">&nbsp;</th><th><b>Title</th><th><b>Description</th><th nowrap><b>Sub-Page Name</th><th width="60px">&nbsp;</th>
				</thead>
				<?php  $i = (isset($this->pager)) ? $this->pager['offset'] + 1 : 1;  foreach($this->data as $v): 
                   $dto = $this->getDto($v);
				?>
				<tr <?php echo  $this->setAltBg($i);?> ><td><input type="checkbox" name="delete[]" value="<?php echo  $dto->getField($this->primaryKey);?>"/> <?php echo  $i;?></td>
				<td><?php echo  $dto->getField('item_title');?></td>
					<td valign='top'><?php echo  $dto->getField('item_desc');?>&nbsp;</td>
					<!--<td valign='top'><?php //echo  $dto->getField('item_cat');?>&nbsp;</td>-->
					<td valign='top'><?php echo  $dto->getField('item_subcat');?>&nbsp;</td>
					<td valign='top'><nobr><a href="#" onclick="if(confirm('The item will be removed completely!'))self.location = '<?php echo  $this->setUrl(array('eid'=>$dto->getField($this->primaryKey),'pagename'=>$this->contentPageName),'delete');?>';">
						<img  src="<?php echo $this->getBaseUrl();?>/freedom/images/delete.png" align='right' border=0 title="Delete" alt='Delete'/>
					    </a> 
					    <a href="<?php echo $this->setUrl(array('eid'=>$dto->getField($this->primaryKey)),'edit');?>">
					    	<img src="<?php echo $this->getBaseUrl();?>/freedom/images/edit.png" border=0 title="Edit" alt='Edit'/></a>&nbsp;&nbsp;&nbsp;</nobr>
					    	
					</td>
				</tr>
			<?php  $i++; endforeach ?>
		</table>
		<div align="right" class="tinyText"><input type="checkbox" value="0" onclick="doSelect('list','delete[]',this.checked)"> Select or unselect all items <input type="submit"  value="Delete Selected"></div>
		</form>
		<?php if($this->pager):
	        echo $this->contentPager($this->pager);
		endif;
		?>
             <?php  else: ?>
                No sub-pages found.
             <?php  endif ?>
	</p>
